sudo: false
language: node_js
cache:
  directories:
    - node-modules
notifications:
  email: true
node_js:
  - stable
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
services:
  - mongodb


